package:
  name: pdfium-build
  version: "7073"
  epoch: 0
  description: "The PDF library used by the Chromium project"
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - busybox
      - build-base
      - wolfi-base
      - ninja-build
      - bash
      - curl
      - python3

pipeline:
  - uses: git-checkout
    with:
      repository: https://chromium.googlesource.com/chromium/tools/depot_tools.git
      destination: ./depot-tools

  - runs: |
      DEPOT_TOOLS_UPDATE=0
      DEPOT_TOOLS_WIN_TOOLCHAIN=0
      export PATH=$PATH:$PWD/depot-tools
      gclient config --unmanaged https://pdfium.googlesource.com/pdfium.git
      echo "target_os = [ 'linux' ]" >> .gclient
      gclient sync -r origin/chromium/${{package.version}} --no-history --shallow
      OPWD=$PWD
      cd pdfium && git reset --hard && git clean -df && cd $OPWD
      cd pdfium/build && git reset --hard && git clean -df && cd $OPWD
      cd pdfium/third_party/libjpeg_turbo && git reset --hard && git clean -df && cd $OPWD
      cd pdfium/base/allocator/partition_allocator && git reset --hard && git clean -df && cd $OPWD
      sed -i 's/component("pdfium") {/shared_library("pdfium") {/g' pdfium/BUILD.gn
      sed -i 's/#if defined(COMPONENT_BUILD)\n\/\/ FPDF_EXPORT should be consistent with |export| in the pdfium_fuzzer\n\/\/ template in testing\/fuzzers\/BUILD.gn.//g' pdfium/public/fpdfview.h
      sed -i 's/#else\n#define FPDF_EXPORT\n#endif  \/\/ defined(COMPONENT_BUILD)//g' pdfium/public/fpdfview.h
      cd pdfium
      gn gen out --args='is_debug=false pdf_use_partition_alloc=false target_cpu="x64" target_os="linux" pdf_enable_v8=false pdf_enable_xfa=false treat_warnings_as_errors=false is_component_build=false symbol_level=0 clang_use_chrome_plugins=false pdf_is_standalone=true'
      ninja -C out pdfium -v

update:
  enabled: true
  release-monitor:
    identifier: 377295